name: is.js CICD

on:
  push:
    branches:
      - develop
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  documentation:
    name: Attach Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'false'

      - name: Attach Documentation
        run: cat .github/workflows/README.md >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        node-version: [14, 16, 18, 20, 22]

    name: is.js - nodeJS v${{ matrix.node-version }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Init - node v${{ matrix.node-version }}
        run: yarn --frozen-lockfile --non-interactive

      - name: Lint - node v${{ matrix.node-version }}
        run: yarn lint

      - name: Test - node v${{ matrix.node-version }}
        run: yarn test

      - name: Build - node v${{ matrix.node-version }}
        run: yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_KEY }}
          NODE_MAJOR_VERSION: ${{ matrix.node-version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kj4ezj-is-${{ matrix.node-version }}
          path: kj4ezj-is-*.tgz
